---
- name: Install packages
  become: yes  # <--- CRITICAL: You need root privileges to install software
  apt:
    name:
    - apache2
    - php
    - libapache2-mod-php
    - php-mysql
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Start and Enable Apache service
  become: yes  # <--- CRITICAL: You need root privileges to manage services
  service:
    name: apache2
    state: started
    enabled: yes
