---
- name: Delete index.html file
  become: yes
  file:
    path: /var/www/html/index.html
    state: absent

- name: Upload application file
  become: yes
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    mode: '0755'
  notify:
    - restart apache2
